version: 2.1
 
jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run test
          command: 'ruby test_sum.rb'
 
workflows:
  test-workflow:
    jobs:
      - test